# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Infection Alert' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infection Alert
# add the Firebase pod for Google Analytics

  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
end

target 'Infection Alert WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infection Alert WatchKit App

end

target 'Infection Alert WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infection Alert WatchKit Extension

end
